# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarID', models.IntegerField()),
                ('Code', models.CharField(max_length=2)),
                ('Value', models.IntegerField()),
            ],
        ),
    ]
